on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-and-push-action@v2
        with:
          push: true
          tags: ghcr.io/tfausak/haskell-codespace:${{ github.sha }}
