name: Docker
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:commit-${{ github.sha }}
            ghcr.io/${{ github.repository }}:ghc-9.2.1
            ghcr.io/${{ github.repository }}:ghc-9.2
